name: ecomapp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#------------- Packages ---------#


dependencies:
  flutter:
    sdk: flutter

  
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2

#------------- Utility Packages ---------#

  
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0

  #State Management
  
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  font_awesome_flutter: ^10.7.0
  razorpay_flutter: ^1.3.6
  fluttertoast: ^8.2.4


#------------- Packages END ---------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  #------------- Local Assets ---------#


  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/onboarding_images/

#------------- Local Fonts ---------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 700

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800