name: ecomapp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#------------- Packages ---------#


dependencies:
  flutter:
    sdk: flutter

  
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12

#------------- Utility Packages ---------#

  
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  
  get: ^4.6.5
  get_storage: ^2.1.1


#------------- Packages END ---------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  #------------- Local Assets ---------#


  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

#------------- Local Fonts ---------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 700

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800