// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh2xoURYFa1jIPevUHWGr4YIBBB2Xiv50',
    appId: '1:265720157858:web:41d86b006043344012a9fb',
    messagingSenderId: '265720157858',
    projectId: 'lokalshop-24d55',
    authDomain: 'lokalshop-24d55.firebaseapp.com',
    storageBucket: 'lokalshop-24d55.appspot.com',
    measurementId: 'G-5HR1STEQPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnWIhSaTC6nCqNZYPC9-pM84Di_vKEqiY',
    appId: '1:265720157858:android:95112522965fb40112a9fb',
    messagingSenderId: '265720157858',
    projectId: 'lokalshop-24d55',
    storageBucket: 'lokalshop-24d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4z4wo--QEiNIeMR8ovwsoZkv-_TJqo5E',
    appId: '1:265720157858:ios:9a9b246b7ad79daf12a9fb',
    messagingSenderId: '265720157858',
    projectId: 'lokalshop-24d55',
    storageBucket: 'lokalshop-24d55.appspot.com',
    iosBundleId: 'com.example.ecomapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4z4wo--QEiNIeMR8ovwsoZkv-_TJqo5E',
    appId: '1:265720157858:ios:484c074293dd078112a9fb',
    messagingSenderId: '265720157858',
    projectId: 'lokalshop-24d55',
    storageBucket: 'lokalshop-24d55.appspot.com',
    iosBundleId: 'com.example.ecomapp.RunnerTests',
  );
}
